version: '3.8'

services:
  db:
    image: postgres
    container_name: todo-pg-container
    ports:
      - 7432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
